### ISSUE TITLE
Compile error with Zig 0.13.0

### ISSUE THREAD

**Issue by COD3HUNT3R** [kubkon/zelf#9]
Currently if I am try to compile with Zig 0.13.0 it gives error that might not be very useful to someone.

```
src/Object.zig:22:38: error: root struct of file 'elf' has no member named 'Versym'
versymtab: std.ArrayListUnmanaged(elf.Versym) = .{},
                                  ~~~^~~~~~~
/home/hunter/bin/lib/std/elf.zig:1:1: note: struct declared here
//! Executable and Linkable Format.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    Object: src/Archive.zig:288:24
    Archive: src/Archive.zig:6:45
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
src/main.zig:343:41: error: no field named 'struct' in union 'builtin.Type'
        const bits = @typeInfo(@This()).@"struct".fields.len;
```

Would you mind adding version requirement and error out like bun did?
https://github.com/oven-sh/bun/blob/f24e8cb98a5db32467a22b829373118fed77b119/build.zig#L22
